-- Tabela TendenciasGastos
CREATE TABLE TendenciasGastos (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Ano NUMBER NOT NULL,
    GastoMarketing NUMBER(10, 2) NOT NULL,
    GastoAutomacao NUMBER(10, 2) NOT NULL
);

-- Tabela DesempenhoFinanceiro
CREATE TABLE DesempenhoFinanceiro (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Receita NUMBER(15, 2) NOT NULL,
    Lucro NUMBER(15, 2) NOT NULL,
    Crescimento NUMBER(5, 2) NOT NULL
);

-- Tabela ComportamentoNegocios
CREATE TABLE ComportamentoNegocios (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    InteracoesPlataforma NUMBER NOT NULL,
    FrequenciaUso NUMBER NOT NULL,
    Feedback VARCHAR2(255) NOT NULL,
    UsoRecursosEspecificos VARCHAR2(255) NOT NULL
);
